"""create processed_stripe_events table

Revision ID: 51a91d9a5fa4
Revises: 3b2c5c0f5cbf
Create Date: 2026-02-28 18:35:42.413477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a91d9a5fa4'
down_revision: Union[str, Sequence[str], None] = '3b2c5c0f5cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_stripe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_stripe_events_id'), 'processed_stripe_events', ['id'], unique=False)
    op.create_index(op.f('ix_processed_stripe_events_stripe_event_id'), 'processed_stripe_events', ['stripe_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_stripe_events_stripe_event_id'), table_name='processed_stripe_events')
    op.drop_index(op.f('ix_processed_stripe_events_id'), table_name='processed_stripe_events')
    op.drop_table('processed_stripe_events')
    # ### end Alembic commands ###
