"""add current_period_end to users

Revision ID: 8a4791884e25
Revises: 7c7fdf9b7dc8
Create Date: 2026-02-27 19:45:01.243262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4791884e25'
down_revision: Union[str, Sequence[str], None] = '7c7fdf9b7dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_period_end')
    # ### end Alembic commands ###
